apiVersion: v1
kind: PersistentVolume
metadata:
  name: aichat-vector-store-pv
  namespace: apc-be-ns
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/aichat-vector-store
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aichat-vector-store-pvc
  namespace: apc-be-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

