apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor
  namespace: apc-cicd-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
  template:
    metadata:
      labels:
        app: harbor
    spec:
      containers:
      - name: harbor
        image: goharbor/harbor-core:v2.10.0 # 예시 버전
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: apc-cicd-ns
spec:
  type: ClusterIP
  ports:
  - port: 30000      # 시방서 정의 포트
    targetPort: 8080
  selector:
    app: harbor
