[all]
a-master1 ansible_host=192.168.0.170
a-master2 ansible_host=192.168.0.171
a-master3 ansible_host=192.168.0.172
a-worker1 ansible_host=192.168.0.173
a-worker2 ansible_host=192.168.0.174
a-worker3 ansible_host=192.168.0.175
a-worker4 ansible_host=192.168.0.176
a-worker5 ansible_host=192.168.0.177

[all:vars]
ansible_user=alphacar
ansible_password=123
ansible_become_password=123
ansible_become=yes
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

